[supabase]
url = "https://twhkodokjocxhgfqgymn.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3aGtvZG9ram9jeGhnZnFneW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTUwMTUsImV4cCI6MjA2MzE3MTAxNX0._vADOEnvXu4vuJXZxtZx_EEzRNvsj-_IzYYGn8n7HCM"