[supabase]
url = "https://rvqcciqlpfhxmckewmev.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2cWNjaXFscGZoeG1ja2V3bWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDM2MDQsImV4cCI6MjA2MzExOTYwNH0.srYg2h8Vtf3NGvoARCX-UsLW8Rj0NcFEZypJ3QgJftU"